%YAML 1.1
# vim: set encoding=utf-8 tabstop=4 softtabstop=4 shiftwidth=4 expandtab
---

plugin:
    # Global plugin attributes
    type: gateway
    description:
        de: 'MultiDevice-Plugin'
        en: 'MultiDevice-Plugin'
    maintainer: Morg
    tester: OnkelAndy
    state: develop
    keywords: iot device
    # documentation: https://github.com/smarthomeNG/smarthome/wiki/MultiDevice-Plugin
    # support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 0.1.0
    sh_minversion: 1.8.2
    py_minversion: 3.6
    multi_instance: false
    restartable: true
    classname: MultiDevice

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    devices:
        type: list
        description:
            de: 'Liste von Geräten (<Geräte-ID> oder <Geräte-ID>: <Geräte-Typ> oder <Geräte-ID>: <Gerätetyp>, <Arg1>=<Wert1>, ...)'
            en: 'List of devices (<device-id> oder <device-id>: <device-name> or <device-id>: <device-name>, <attr1>=<val1>, ...)'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

    md_deviceid:
        type: str
        description:
            de: 'Weist dem Item das Gerät mit dem angegebenen Namen zu'
            en: 'Assigns the item to the device with the supplied name'

    md_command:
        type: str
        description:
            de: 'Legt das angegebene Kommando für das Item fest'
            en: 'Assigns the given command to the item'
    md_read:
        type: str
        description:
            de: 'Liest/erhält Werte vom Gerät'
            en: 'Reads/receives data from the device'

    md_read_group:
        type: int
        description:
            de: 'Weist das Item der angegebenen Gruppe zum gesammelten Lesen zu'
            en: 'Assigns the item to the given group for collective reading'

    md_read_cycle:
        type: num
        description:
            de: 'Konfiguriert ein Intervall in Sekunden für regelmäßiges Lesen'
            en: 'Configures a interval in seconds for cyclic read actions'

    md_read_initial:
        type: bool
        description:
            de: 'Legt fest, dass der Wert beim Start vom Gerät gelesen wird'
            en: 'Sets item value to be read from the device on startup'

    md_write:
        type: str
        description:
            de: 'Änderung des Items werden an das Gerät gesendet'
            en: 'Changes to this item will be sent to the device'

    md_read_all_trigger:
        type: bool
        description:
            de: 'Wenn diesem Item ein beliebiger Wert zugewiesen wird, werden alle zum Lesen konfigurierten Items neu vom Gerät gelesen. Das Item kann nicht gleichzeitig mit md_command belegt werden.'
            en: 'When set to any value, all items configured for reading will update their value from the device. The item cannot be used with md_command in parallel.'

    md_read_group_trigger:
        type: int
        description:
            de: 'Wenn diesem Item ein beliebiger Wert zugewiesen wird, werden alle zum Lesen konfigurierten Items der angegebenen Gruppe neu vom Gerät gelesen. Das Item kann nicht gleichzeitig mit md_command belegt werden.'
            en: 'When set to any value, all items configured for reading for the given group will update their value from the device. The item cannot be used with md_command in parallel.'

    md_lookup:
        type: str
        description:
            de: 'Der Inhalt der Lookup-Tabelle mit dem angegebenen Namen wird beim Start einmalig als dict in das Item geschrieben.'
            en: 'The lookup table with the given name will be assigned to the item in dict format once on startup.'

item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions:
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters:
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
