%YAML 1.1
# vim: set encoding=utf-8 tabstop=4 softtabstop=4 shiftwidth=4 expandtab
---

multidevice:
    plugin_name: priv_multidevice
    device:
        - dev1
        - dev2:
              - name: DEV
              - host: werkpi
              - port: 8384
        - dev4: abc
